### ISSUE TITLE
Some error messages are ommitted with NODE_ENV=production

### ISSUE THREAD

**Issue by braydonf** [Storj/service-error-types#4]
With NODE_ENV=production error messages are replaced from the defaults set in these definitions. While in some cases this is desirable (to not reveal too much info), in other times it's not. 

401 Unauthorized will just be "Unauthorized" instead of "Incorrect email or password", and with custom status codes (e.g. 420) the message will be undefined.

This is related to how [restify is handling errors](http://restify.com/#error-handling).

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
